##這好像是一個api，用來模擬postman的功能，用來模擬瀏覽器的行為。有固定格式，Content-Type的下兩行寫key跟value
GET http://localhost:3002/try-qs?a=1&b=22

###分隔

POST http://localhost:3002/try-post
Content-Type: application/x-www-form-urlencoded

a=10&name=bill&c=2ㄇ

###分隔

POST http://localhost:3002/try-post
Content-Type: application/json

{"a":10,"name":"bill","c":2}